### ISSUE TITLE
[IME transition] サンプル確認

### ISSUE THREAD

**Issue by mag0716** [mag0716/Android11_CatchUp#13]
## 概要

https://github.com/android/user-interface-samples/tree/master/WindowInsetsAnimation
の実装、動作を確認する。

## 参考

* https://proandroiddev.com/exploring-windowinsets-on-android-11-a80cf8fe19be
* https://blog.stylingandroid.com/android11-windowinsets-part1/

**Comment by mag0716** [comment]
## コードリーディング

* `Window#setDecorFitsSystemWindow(false)` でコンテンツ領域を画面全体に表示する必要がある
* `RootViewDeferringInstesCallback`
    * `WIndowInsetsAnimation.Callback` と `View.OnApplyWindowInsetsListener` を実装
    * 子Viewにもサイズ変更を通知するために `DISPATCH_MODE_CONTINUE_ON_SUBTREE` を利用
    * サンプルではステータスバーやナビゲーションバーの固定の領域とIMEの領域分をパディングとして `Fragment` のパディングを更新している
    * これをルートViewにセットすることで正しい領域にコンテンツを表示されるようになる
    * ただしアニメーションはIMEのアニメーションと同期しない
* `TranslateDeferringInsetsAnimationCallback`
    * `WindowInsetsAnimation.Callback` を実装
    * 自身のViewの変更のみでよいので、`DISPATCH_MODE_STOP` を利用
    * IME の表示量からViewの移動量をセットしてIMEのアニメーションと同期して動作するようにしている
* `InsetsAnimationOverscrollingTouchListener`
    * スクロールによって IME を表示、非表示にするために必要(なくてもよい)
    * ユーザ操作をハンドリングしてIMEをアニメーション開始タイミングを `SimpleImeAnimationController` 経由で通知している
* `SimpleImeAnimationController`
    * `WindowInsetsController#controlWindowInsetsAnimation` をセットし、加速度や `WindowInsetsAnimationControlListener` に指定する
    * スクロール中は `InsetsAnimationOverscrollingTouchListener` から `updateInsetTo` が呼ばれ、`WindowInsetsAnimationController#setInsetsAndAplha` 経由で Inset が更新される

**Comment by mag0716** [comment]
スクロールでの IME の表示、非表示は

```
2020-05-09 21:49:12.691 7460-7460/com.google.android.samples.insetschat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.samples.insetschat, PID: 7460
    java.lang.IllegalStateException: Current WindowInsetsAnimationController is null.This should only be called if isAnimationInProgress() returns true
        at com.google.android.samples.insetsanimation.SimpleImeAnimationController.updateInsetTo(SimpleImeAnimationController.kt:136)
        at com.google.android.samples.insetsanimation.SimpleImeAnimationController$animateImeToVisibility$animator$1.invoke(SimpleImeAnimationController.kt:265)
        at com.google.android.samples.insetsanimation.SimpleImeAnimationController$animateImeToVisibility$animator$1.invoke(SimpleImeAnimationController.kt:40)
        at androidx.dynamicanimation.animation.DynamicAnimationKt$createFloatValueHolder$1.setValue(DynamicAnimation.kt:83)
        at androidx.dynamicanimation.animation.DynamicAnimation$15.setValue(DynamicAnimation.java:349)
        at androidx.dynamicanimation.animation.DynamicAnimation.setPropertyValue(DynamicAnimation.java:706)
        at androidx.dynamicanimation.animation.DynamicAnimation.doAnimationFrame(DynamicAnimation.java:667)
        at androidx.dynamicanimation.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:158)
        at androidx.dynamicanimation.animation.AnimationHandler$AnimationCallbackDispatcher.dispatchAnimationFrame(AnimationHandler.java:61)
        at androidx.dynamicanimation.animation.AnimationHandler$FrameCallbackProvider16$1.doFrame(AnimationHandler.java:207)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7476)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:939)
```

でクラッシュすることがある。
